### ISSUE TITLE
[Feature Suggestion] Headless Identification

### ISSUE THREAD

**Issue by reality-exe** [Nutcake/contacts-plus-plus#15]
Maybe having small text in the corner or next to the display name of the account saying `[Headless]`.

In the status portion of the API the output device shows if it's a Headless.

Maybe this could also be used to identify everyone.

**Comment by Nutcake** [comment]
Good idea! I'll probably have it just show a small icon after the contacts name if it is a headless user.

**Comment by Nutcake** [comment]
Added in 8a6a033cfdb9bb63ad14fff3f5d5654a9f863305
