### ISSUE TITLE
Session filter settings reset after app restart

### ISSUE THREAD

**Issue by 5H4D0W-X** [Nutcake/contacts-plus-plus#25]

**Comment by Nutcake** [comment]
Hm is this not desired behaviour? I feel like it might be confusing to have sessions get filtered out because of old filter settings after a fresh start.

**Comment by 5H4D0W-X** [comment]
I think at least the default state should be configurable, because always needing to turn minimum players to 1 gets annoying after a while. Alternatively, why not implement a watered-down selector like in Neos, where you can choose between all sessions, active sessions and contacts sessions?

**Comment by Nutcake** [comment]
Added filter settings caching in v1.5.0
