### ISSUE TITLE
[Feature Request] Add 360 photo panning to session previews

### ISSUE THREAD

**Issue by dfgHiatus** [Nutcake/contacts-plus-plus#26]
I'm a big fan of being able to preview sessions by image. It would be very nice to "look" around a session, similar to how Neos already does this in-game.

I propose this feature be added as opt-in, with a setting to toggle this on and off. 

*I've also considered the possibility of using phone gyro to look around? I also propose we use this thread to discuss this here

**Comment by Nutcake** [comment]
This is a cool idea, added it in the latest release (v1.5.0).
Thank you for the suggestion!
