### ISSUE TITLE
Material You Icon

### ISSUE THREAD

**Issue by reality-exe** [Nutcake/contacts-plus-plus#27]
Would it be possible to get the material you Icon for pixel (and whatever else can use it) devices?

![Screenshot_20230718-141335.png](https://github.com/Nutcake/contacts-plus-plus/assets/95439036/e7d578cf-f0b3-4adf-a423-d195bb5a1432)

**Comment by reality-exe** [comment]
Wow i wasnt expecting the image to take up that much space. Thought it would shrink down to a reasonable size lol

**Comment by Nutcake** [comment]
Should be doable, I can look into this on the weekend

**Comment by Nutcake** [comment]
Added in v1.5.1
